api_platform:
    title: 'Symfony REST API for projet Platine - Application zoo de Lille'
    description: 'A Symfony API to manage the zoo information'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
